-- Global permission catalogue (mirrors PermissionKeys.java)
insert into permissions (id, key, name, category) values
 (gen_random_uuid(), 'LEAD_VIEW', 'View leads', 'Leads'),
 (gen_random_uuid(), 'LEAD_CREATE', 'Create leads', 'Leads'),
 (gen_random_uuid(), 'LEAD_UPDATE', 'Update leads', 'Leads'),
 (gen_random_uuid(), 'LEAD_DELETE', 'Delete leads', 'Leads'),
 (gen_random_uuid(), 'LEAD_ASSIGN', 'Assign leads', 'Leads'),
 (gen_random_uuid(), 'LEAD_EXPORT', 'Export leads', 'Leads'),
 (gen_random_uuid(), 'LEAD_CONVERT', 'Convert leads to clients', 'Leads'),
 (gen_random_uuid(), 'LEAD_IMPORT', 'Import leads', 'Leads'),
 (gen_random_uuid(), 'IMPORT_VIEW', 'View import history', 'Leads'),
 (gen_random_uuid(), 'COMPANY_VIEW', 'View companies', 'Companies'),
 (gen_random_uuid(), 'COMPANY_CREATE', 'Create companies', 'Companies'),
 (gen_random_uuid(), 'COMPANY_UPDATE', 'Update companies', 'Companies'),
 (gen_random_uuid(), 'COMPANY_DELETE', 'Delete companies', 'Companies'),
 (gen_random_uuid(), 'CONTACT_VIEW', 'View contacts', 'Contacts'),
 (gen_random_uuid(), 'CONTACT_CREATE', 'Create contacts', 'Contacts'),
 (gen_random_uuid(), 'CONTACT_UPDATE', 'Update contacts', 'Contacts'),
 (gen_random_uuid(), 'CONTACT_DELETE', 'Delete contacts', 'Contacts'),
 (gen_random_uuid(), 'CALL_VIEW', 'View calls', 'Calls'),
 (gen_random_uuid(), 'CALL_CREATE', 'Log calls', 'Calls'),
 (gen_random_uuid(), 'TASK_VIEW', 'View tasks', 'Tasks'),
 (gen_random_uuid(), 'TASK_CREATE', 'Create tasks', 'Tasks'),
 (gen_random_uuid(), 'TASK_UPDATE', 'Update tasks', 'Tasks'),
 (gen_random_uuid(), 'TASK_DELETE', 'Delete tasks', 'Tasks'),
 (gen_random_uuid(), 'MEETING_VIEW', 'View meetings', 'Meetings'),
 (gen_random_uuid(), 'MEETING_CREATE', 'Create meetings', 'Meetings'),
 (gen_random_uuid(), 'MEETING_UPDATE', 'Update meetings', 'Meetings'),
 (gen_random_uuid(), 'MEETING_DELETE', 'Delete meetings', 'Meetings'),
 (gen_random_uuid(), 'EMAIL_VIEW', 'View emails', 'Email'),
 (gen_random_uuid(), 'EMAIL_SEND', 'Send emails', 'Email'),
 (gen_random_uuid(), 'EMAIL_ACCOUNT_VIEW', 'View email accounts', 'Email'),
 (gen_random_uuid(), 'EMAIL_ACCOUNT_CREATE', 'Connect email accounts', 'Email'),
 (gen_random_uuid(), 'EMAIL_ACCOUNT_UPDATE', 'Update email accounts', 'Email'),
 (gen_random_uuid(), 'EMAIL_ACCOUNT_DELETE', 'Remove email accounts', 'Email'),
 (gen_random_uuid(), 'TEMPLATE_VIEW', 'View email templates', 'Email'),
 (gen_random_uuid(), 'TEMPLATE_CREATE', 'Create email templates', 'Email'),
 (gen_random_uuid(), 'TEMPLATE_UPDATE', 'Update email templates', 'Email'),
 (gen_random_uuid(), 'TEMPLATE_DELETE', 'Delete email templates', 'Email'),
 (gen_random_uuid(), 'CAMPAIGN_VIEW', 'View campaigns', 'Campaigns'),
 (gen_random_uuid(), 'CAMPAIGN_CREATE', 'Create campaigns', 'Campaigns'),
 (gen_random_uuid(), 'CAMPAIGN_UPDATE', 'Update campaigns', 'Campaigns'),
 (gen_random_uuid(), 'CAMPAIGN_SEND', 'Start/stop campaigns', 'Campaigns'),
 (gen_random_uuid(), 'DEAL_VIEW', 'View deals', 'Sales'),
 (gen_random_uuid(), 'DEAL_CREATE', 'Create deals', 'Sales'),
 (gen_random_uuid(), 'DEAL_UPDATE', 'Update deals', 'Sales'),
 (gen_random_uuid(), 'DEAL_DELETE', 'Delete deals', 'Sales'),
 (gen_random_uuid(), 'PROPOSAL_VIEW', 'View proposals', 'Sales'),
 (gen_random_uuid(), 'PROPOSAL_CREATE', 'Create proposals', 'Sales'),
 (gen_random_uuid(), 'PROPOSAL_UPDATE', 'Update proposals', 'Sales'),
 (gen_random_uuid(), 'PROPOSAL_DELETE', 'Delete proposals', 'Sales'),
 (gen_random_uuid(), 'PROPOSAL_SEND', 'Send proposals', 'Sales'),
 (gen_random_uuid(), 'CLIENT_VIEW', 'View clients', 'Clients'),
 (gen_random_uuid(), 'CLIENT_UPDATE', 'Update clients', 'Clients'),
 (gen_random_uuid(), 'DOCUMENT_VIEW', 'View documents', 'Documents'),
 (gen_random_uuid(), 'DOCUMENT_CREATE', 'Upload documents', 'Documents'),
 (gen_random_uuid(), 'DOCUMENT_DELETE', 'Delete documents', 'Documents'),
 (gen_random_uuid(), 'PIPELINE_VIEW', 'View pipelines', 'Configuration'),
 (gen_random_uuid(), 'PIPELINE_UPDATE', 'Manage pipelines', 'Configuration'),
 (gen_random_uuid(), 'TAG_VIEW', 'View tags', 'Configuration'),
 (gen_random_uuid(), 'TAG_UPDATE', 'Manage tags', 'Configuration'),
 (gen_random_uuid(), 'SOURCE_VIEW', 'View lead sources', 'Configuration'),
 (gen_random_uuid(), 'SOURCE_UPDATE', 'Manage lead sources', 'Configuration'),
 (gen_random_uuid(), 'SCORING_VIEW', 'View scoring rules', 'Configuration'),
 (gen_random_uuid(), 'SCORING_UPDATE', 'Manage scoring rules', 'Configuration'),
 (gen_random_uuid(), 'AUTOMATION_VIEW', 'View automations', 'Configuration'),
 (gen_random_uuid(), 'AUTOMATION_UPDATE', 'Manage automations', 'Configuration'),
 (gen_random_uuid(), 'AI_USE', 'Use AI assistant', 'AI'),
 (gen_random_uuid(), 'REPORT_VIEW', 'View dashboards & reports', 'Analytics'),
 (gen_random_uuid(), 'AUDIT_VIEW', 'View audit logs', 'Administration'),
 (gen_random_uuid(), 'USER_VIEW', 'View users', 'Administration'),
 (gen_random_uuid(), 'USER_CREATE', 'Create users', 'Administration'),
 (gen_random_uuid(), 'USER_UPDATE', 'Update users', 'Administration'),
 (gen_random_uuid(), 'USER_DELETE', 'Delete users', 'Administration'),
 (gen_random_uuid(), 'ROLE_VIEW', 'View roles', 'Administration'),
 (gen_random_uuid(), 'ROLE_CREATE', 'Create roles', 'Administration'),
 (gen_random_uuid(), 'ROLE_UPDATE', 'Update roles', 'Administration'),
 (gen_random_uuid(), 'ROLE_DELETE', 'Delete roles', 'Administration'),
 (gen_random_uuid(), 'TEAM_VIEW', 'View teams', 'Administration'),
 (gen_random_uuid(), 'TEAM_CREATE', 'Create teams', 'Administration'),
 (gen_random_uuid(), 'TEAM_UPDATE', 'Update teams', 'Administration'),
 (gen_random_uuid(), 'TEAM_DELETE', 'Delete teams', 'Administration'),
 (gen_random_uuid(), 'ORG_VIEW', 'View organization', 'Administration'),
 (gen_random_uuid(), 'ORG_UPDATE', 'Update organization', 'Administration'),
 (gen_random_uuid(), 'SETTINGS_VIEW', 'View settings', 'Administration'),
 (gen_random_uuid(), 'SETTINGS_UPDATE', 'Update settings', 'Administration')
on conflict (key) do nothing;
