package com.crm.modules.activity.domain;

public enum ActivityType {
    NOTE, CALL, INCOMING_CALL, OUTGOING_CALL, EMAIL, EMAIL_REPLY, WHATSAPP,
    MEETING, DEMO, PROPOSAL, OFFER, FOLLOW_UP, TASK_CREATED, TASK_COMPLETED,
    STATUS_CHANGE, STAGE_CHANGE, ASSIGNMENT_CHANGE, SCORE_CHANGE, LEAD_CREATED,
    CONVERSION, IMPORT, SYSTEM
}
